version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: man_app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: man_app
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  adminer:
    image: adminer
    container_name: man_app_adminer
    ports:
      - "8080:8080"
volumes:
  dbdata:
