// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bymqllifioyhgbqgheuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bXFsbGlmaW95aGdicWdoZXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjQxOTMsImV4cCI6MjA3MDIwMDE5M30.Y0tpntquHjbyti61OT0qG3N0BI0GkLGuGFXXT-HfnRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});